accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/<str:username>', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    # post관련 url
    path('', views.posts, name='posts'),
    path('category/<str:subject>/', views.category, name='category'),
    path('<int:post_pk>/', views.post, name='post'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),


    # review관련 url
    path('<int:post_pk>/reviews/<int:review_pk>/', views.review_detail, name='review_detail'),
    path('<int:post_pk>/reviews/', views.review_create , name='review_create'),
    path('<int:post_pk>/reviews/<int:review_pk>/update/', views.review_update, name='review_update'),
    path('<int:post_pk>/reviews/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    path('<int:post_pk>/reviews/<int:review_pk>/likes/', views.review_likes, name='review_likes',),
    # path('<int:post_pk>/emotes/<int:emotion>/', views.emotes, name='emotes'),


    # comment관련 url
    path('<int:post_pk>/reviews/<int:review_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:post_pk>/reviews/<int:review_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),


    # 기타 url
    path('search/', views.search, name="search"),
    path('tags/<int:tag_pk>/', views.tagged, name='tagged'),
    path('<int:post_pk>/recomment/', views.recomment, name='recomment'),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.



class User(AbstractUser):
    profile_image = models.ImageField(blank=True, null=True, upload_to='images/profile/')
    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)

posts/models.py
from django.db import models
import os
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail
from django.conf import settings
from django.utils import timezone
from datetime import timedelta,datetime
from taggit.managers import TaggableManager

# Create your models here.
class Profile(models.Model):
    image = models.ImageField(blank=True, upload_to='images/profile/')
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(200, 200)],
        format='JPEG',
        options={'quality': 80}
    )


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    title = models.CharField(max_length=50)
    address = models.CharField(max_length=30)
    phone_number = models.CharField(max_length=30, blank=True)
    menu = models.CharField(max_length=200)
    hours = models.CharField(max_length=30)
    information = models.CharField(max_length=200, blank=True)
    category = models.CharField(max_length=10)
    image = models.ImageField(blank=True, null=True, upload_to='images/post/%Y/%m/%d/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager(blank=True)


    def str(self):
        return self.title
    
    def count_likes_user(self):
        return self.like_users.count()

    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, str(self.image)))
        super(Post, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_post = Post.objects.get(id=self.id)
            if self.image != old_post.image:
                if old_post.image:
                    os.remove(os.path.join(settings.MEDIA_ROOT, str(old_post.image.path)))
        super(Post, self).save(*args, **kwargs)

    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    image = models.ImageField(blank=True, null=True, upload_to='images/review/%Y/%m/%d/')
    content = models.CharField(max_length=200)
    rating = models.FloatField(verbose_name='평점')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def star_rating(self):
        rounded_rating = self.rating
        return '⭐' * int(rounded_rating) + '☆' * (rounded_rating % 1 == 0.5)
    
    def count_likes_user(self):
        return self.like_users.count()
    
    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, str(self.image)))
        super(Review, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_review = Review.objects.get(id=self.id)
            if self.image != old_review.image:
                if old_review.image:
                    os.remove(os.path.join(settings.MEDIA_ROOT, str(old_review.image.path)))
        super(Review, self).save(*args, **kwargs)

    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False


class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')
    content = models.CharField(max_length=200)
    parent_comment = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def count_likes_user(self):
        return self.like_users.count()
    
    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False
    
    
class ReviewPhoto(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='reviews/photos/')
    
    def __str__(self):
        return self.content
    
    def delete(self, *args, **kargs):
        if self.photo:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.photo))
        super(ReviewPhoto, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_reviewPhoto = ReviewPhoto.objects.get(id=self.id)
            if self.photo != old_reviewPhoto.photo:
                if old_reviewPhoto.photo:
                    os.remove(os.path.join(settings.MEDIA_ROOT, old_reviewPhoto.photo.path))
        super(ReviewPhoto, self).save(*args, **kwargs)


class Emote(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    emotion = models.CharField(max_length=10)


class ReComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    content = models.CharField('대댓글', max_length=150)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.forms.widgets import ClearableFileInput
from imagekit.models import ImageSpecField
from imagekit.forms import ProcessedImageField
from imagekit.processors import Thumbnail
from imagekit.processors import ResizeToFill
from django import forms


class CustomUserCreationForm(UserCreationForm):
    # profile_image = ProcessedImageField(
    # spec_id='profile_image_thumbnail',
    # processors=[ResizeToFill(70,70)],
    # format='JPEG',
    # options={'quality' : 90},
    # required=False,
    # )
    
    birthday = forms.DateField(
        label='Birthday',
        required=False,
        widget=forms.DateInput(
        attrs={
            'class' : 'form-control w-100 p-1',
            'type': 'date',
        }
        )
    )
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name', 'birthday', 'password1', 'password2',)
    username = forms.CharField(
        widget= forms.TextInput(
        attrs={
            'class' : 'form-control w-100 p-1',
            'placeholder' : 'id',
        }
        )
    )

    email = forms.EmailField(
        widget= forms.EmailInput(
        attrs={
            'class' : 'form-control w-100 p-1',
            'placeholder' : 'email@example.com',
        }
        )
    )

    first_name = forms.CharField(
        widget=forms.TextInput(
        attrs={
            'class' : 'form-control w-100 p-1',
            'placeholder' : 'firstname',
        }
        )
    )

    last_name = forms.CharField(
        widget=forms.TextInput(
        attrs={
            'class' : 'form-control w-100 p-1',
            'placeholder' : 'lastname',
        }
        )
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput({
        'class' : 'form-control w-100 p-1',
        'placeholder' : 'password'
        }
        )
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput({
        'class' : 'form-control w-100 p-1',
        'placeholder' : 'password'
        }
        )
    )

class CustomUserChangeForm(UserChangeForm):
    profile_image = ProcessedImageField(
        spec_id='profile_image_thumbnail',
        processors=[ResizeToFill(70,70)],
        format='JPEG',
        options={'quality' : 90},
        required=False,
        widget=ClearableFileInput(
        attrs={
            'class': 'form-control',
            'id': 'profile_image',
            'name': 'profile_image'
        }
        ),
    )
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            'email',
            'first_name',
            'last_name',
            'profile_image',
        )
    email = forms.EmailField(
        label='Email address',
        widget= forms.EmailInput(
        attrs={
            'class' : 'form-control w-100 p-2',
            'placeholder' : 'email@example.com',
        }
        )
    )

    first_name = forms.CharField(
        label="First name",
        widget=forms.TextInput(
        attrs={
            'class' : 'form-control w-100 p-2',
            'placeholder' : 'firstname',
        }
        )
    )

    last_name = forms.CharField(
        label="Last name",
        widget=forms.TextInput(
        attrs={
            'class' : 'form-control w-100 p-2',
            'placeholder' : 'lastname',
        }
        )
    )

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control w-100 p-2 mb-2',
                'placeholder': '아이디',
            },
        ),
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control w-100 p-2',
                'type': 'password',
                'placeholder': '비밀번호',
            },
        ),
    )

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from .forms import CustomUserCreationForm, CustomUserChangeForm, CustomAuthenticationForm
from django.http import JsonResponse

# Create your views here.
def profile(request, username):
    User = get_user_model()
    person = get_object_or_404(User, username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def follow(request, user_pk):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)
    
    if person != request.user:
        if request.user in person.followers.all():
            person.followers.remove(request.user)
            is_followed = False
        else:
            person.followers.add(request.user)
            is_followed = True
        context = {
            'is_followed' : is_followed,
            'followings_count': person.followings.count(),
            'followers_count': person.followers.count(),
        }
        return JsonResponse(context)
    return redirect('accounts:profile', person.username)


def login(request):
    if request.user.is_authenticated:
        return redirect('index')

    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('index')
    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('index')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form':form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form':form,
    }
    return render(request, 'accounts/change_password.html', context)

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
<title>{{ person.username }}님의 프로필</title>
<link rel="stylesheet" href="{% static 'accounts/css/profile.css' %}">
{% endblock style %}


{% block content %}
<main class="profile-main d-flex align-items-center">
  <div class="container container d-flex flex-column align-items-center px-0">
    <!-- profile tilte -->
    <div class="d-flex justify-content-center align-items-center position-relative my-5 w-100">
      <a class="position-absolute start-0 ms-5 btn btn-outline-secondary" href="{% url 'index' %}">뒤로 가기</a>
      <h2 class="fw-bold">{{ person.username }}님의 프로필</h2>
    </div>
    <!-- profile main -->
    <div class="row my-auto">
      <!-- user profile -->
      <section class="user-profile col-3 d-flex justify-content-center">
        <div class="user-info-container d-flex flex-column align-items-center w-75">
          <div class="user-info mt-4 mb-5 d-flex flex-column align-items-center">
            <div class="user-info__avatar w-75 mb-4 rounded-circle d-flex flex-column align-items-center justify-content-center">
              {% if person.profile_image %}
                <img class="w-100 rounded-circle" src="{{ person.profile_image.url }}" alt="프로필이미지">
              {% else %}
                <img class="w-100 rounded-circle" src="{% static 'accounts/img/no_profile.jpeg' %}" alt="기본 프로필 이미지">
              {% endif %}
            </div>
            <div class="user-info__id mb-3">
              <h3 class="fw-bold m-0 w-100 text-center px-2">{{ person.username }}</h3>
              {% if person.is_admin %}
                <div>(관리자)</div>
              {% endif %}
            </div>
            <!-- user-info__팔로우 및 팔로워 현황-->
            <div class="user-info__follow mb-3">
              <span>팔로워 </span><span id="followers-count">{{ person.followers.all|length }}</span>
              <span> / </span>
              <span>팔로잉 </span><span id="followings-count">{{ person.followings.all|length }}</span>
            </div>
            <!-- user-info__본인 프로필이면 회원정보 수정 / 타인이면 팔로우 버튼 -->
            <div class="w-100">
              {% if request.user == person %}
                <div class="w-100 mb-4 d-flex flex-column align-items-center">
                  <a href="{% url 'accounts:update' %}" class="btn btn-outline-secondary w-75 fw-bold">회원정보 수정</a>
                </div>
              {% else %}
                <form id="follow-form" data-user-id="{{ person.pk }}" class="w-100 mb-4 d-flex flex-column align-items-center">
                  {% csrf_token %}
                  {% if request.user in person.followers.all %}
                    <input class="btn btn-outline-secondary w-75 fw-bold" type="submit" value="언팔로우">
                  {% else %}
                    <input class="btn btn-outline-secondary w-75 fw-bold" type="submit" value="팔로우">
                  {% endif %}
                </form>
              {% endif %}
            </div>
          </div>
          <div class="user-articles-category w-100 mb-4 d-flex flex-column align-items-center">
            <button class="category-btn btn btn-danger w-75 fw-bold mb-3" data-target="#review-content">리뷰</button>
            <button class="category-btn btn btn-secondary w-75 fw-bold mb-3" data-target="#comment-content">댓글</button>
            <button class="category-btn btn btn-secondary w-75 fw-bold" data-target="#like-content">좋아요</button>
          </div>
        </div>
      </section>

      <!-- user content -->
      <section class="user-articles-section col-9 p-0">
        <!-- 작성한 리뷰 -->
        <section id="review-content" class="category-content mb-4" style="display: block;">
          <div>
            <h3 class="user-articles__title mb-4 fw-bold">작성한 리뷰</h3>
            <div class="row" style="min-height: 45rem;">
              {% if person.review_set.all %}
                <div id="map" class="w-100 rounded-3 mb-3 col-12" style="height: 300px;"></div>
                {% for review in person.review_set.all %}
                  <div class="col-6 p-0">
                    <article class="user-article--review p-4 m-1 d-flex justify-content-center row">
                      <!-- 리뷰 이미지-->
                      <div style="width: 7rem; height: 7rem; overflow: hidden;" class="d-flex justify-content-center col-2">
                        {% if review.reviewphoto_set.exists %}
                          <img class="h-100" style="object-fit: contain;" src="{{ review.reviewphoto_set.first.photo.url }}" alt="">
                        {% else %}
                          <img class="h-100" style="object-fit: contain;" src="{% static 'posts/img/no_img.jpg' %}" alt="">
                        {% endif %}
                      </div>
                      <!-- 리뷰 content-->
                      <div class="col-9 px-3 d-flex flex-column justify-content-between">
                        <div class="d-flex" >
                          <span class="me-2">From</span>
                          <h5 class="fw-bold">{{ review.post.title }}</h5>
                        </div>
                        <div class="user-article--review__time mb-2">
                          <span>날짜</span>
                          <time class=""> {{ review.updated_at|date:'Y-m-d' }}</time>
                        </div>
                        <div class="user-article--review__middle mb-3">
                          <div class="user-article--review__middle__desc">{{ review.content }}</div>
                        </div>
                      </div>
                    </article>
                  </div>
                {% endfor %}
              {% else %}
              <div class="w-100 d-flex flex-column justify-contents-center align-items-center my-5">
                <img src="https://img.freepik.com/free-photo/cute-little-dog-impersonating-a-business-person_23-2148985937.jpg" alt="게시글 없음 대체 이미지" class="mb-5">
                <div class="text-center fs-4 fw-bold mb-5">작성한 리뷰가 없네요 <br>대신 귀여운 강아지를 드리겠습니다</div>
              </div>
              {% endif %}
            </div>
          </div>
        </section>
        <!-- 작성한 댓글 리스트-->
        <section id="comment-content" class="category-content mb-4" style="display: none;">
          <div class="user-articles-inner user-articles--review">
            <h3 class="user-commentstitle mb-4 fw-bold">작성한 댓글</h3>
            <div style="min-height: 45rem;">
              {% if person.comment_set.all %}
                {% for comment in person.comment_set.all %}
                  <a class="col" href="" class="p-4 d-block">
                    <div class="w-100 user-article--review mb-2 p-3 d-flex justify-content-between">
                      <span>{{ comment.content }}</span>
                      <span>{{ comment.created_at|date:'Y-m-d' }}</span>
                    </div>
                  </a>
                {% endfor %}
              {% else %}
                <div class="w-100 d-flex flex-column justify-contents-center align-items-center my-5">
                  <img src="https://img.freepik.com/free-photo/cute-little-dog-impersonating-a-business-person_23-2148985937.jpg" alt="게시글 없음 대체 이미지" class="mb-5">
                  <div class="text-center fs-4 fw-bold mb-5">작성한 댓글이 없네요 <br>대신 귀여운 강아지를 드리겠습니다</div>
                </div>
              {% endif %}
            </div>
          </div>
        </section>

        <!-- 좋아요 게시글 관련 리스트-->
        <section id="like-content" class="category-content mb-4" style="display: none;">
          <div class="user-articles-inner user-articles--review">
            <h3 class="user-like-cafe__title mb-4 fw-bold">좋아요한 가게</h3>
            <div style="min-height: 45rem;">
              {% if person.like_posts.all %}
                <div class="user-like-cafe__detail row row-cols-5 g-3">
                {% for post in person.like_posts.all %}
                  <a class="col" href="">
                    <div class="card">
                      <div style="height: 120px; overflow: hidden; object-fit: contain;">
                        <img src="{{ post.image.url }}" class="card-img-top" alt="...">
                      </div>
                      <div class="card-body p-2">
                        <h6 class="card-title fw-bold d-flex align-items-center"> {{ post.title }}</h6>
                        <address class="card-text user-article--review__middle__desc">{{ post.address }}</address>
                      </div>
                    </div>
                  </a>
                {% endfor %}
              {% else %}
              <div class="w-100 d-flex flex-column justify-contents-center align-items-center my-5">
                <img src="https://img.freepik.com/free-photo/cute-little-dog-impersonating-a-business-person_23-2148985937.jpg" alt="게시글 없음 대체 이미지" class="mb-5">
                <div class="text-center fs-4 fw-bold mb-5">좋아요한 가게가 없네요 <br>대신 귀여운 강아지를 드리겠습니다</div>
              </div>
              {% endif %}
              <!-- 샘플 article -->
            </div>
          </div>
        </section>
      </section>
    </div>
  </div>
</main>
{% endblock content %}


{% block script %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=3b8f429608439fe66cf463070bdbdb14&libraries=services"></script>
<script src="{% static 'accounts/js/profile__map.js' %}"></script>
<script src="{% static 'accounts/js/profile__follow-btn.js' %}"></script>
<script src="{% static 'accounts/js/profile__category-btn.js' %}"></script>
{% endblock script %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
<title>회원정보수정</title>
<link rel="stylesheet" href="{% static 'accounts/css/update.css' %}">
{% endblock style %}


{% block content %}
<main class="main--signup d-flex">
    <div class="container my-5 p-0 d-flex flex-column align-items-center">
        <!-- update title -->
        <div class="d-flex justify-content-center align-items-center position-relative mb-5 w-75">
            <a class="position-absolute start-0 ms-5 btn btn-outline-secondary" href="{% url 'accounts:profile' user.username %}">뒤로 가기</a>
            <h2 class="fw-bold">회원정보수정</h2>
        </div>
        <!-- update form -->
        <form class="w-75 mb-4 row d-flex justify-content-center align-items-center" action="{% url 'accounts:update' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- update-name and address -->
            <section class="px-5 border-end col-6 h-100">
                <div style="overflow:hidden;">
                    <label class="mb-2 fs-5 fw-bold" for="profile_image">프로필 이미지</label>
                    <div class="update-image-container my-5 d-flex flex-column justify-content-center align-items-center">
                        {% if user.profile_image %}
                            <img id="preview" class="rounded-circle" style="width: 10rem; height:10rem;" src="{{ user.profile_image.url }}" alt="Profile Image Preview">
                        {% else %}
                            <img id="preview" class="rounded-circle" style="width: 10rem; height:10rem;" src="{% static 'accounts/img/no_profile.jpeg' %}" alt="Profile Image Preview">
                        {% endif %}
                    </div>
                    {{ form.profile_image }}
                </div>
            </section>
            <!-- update-image-->
            <section class="px-5 col-6 h-100 d-flex flex-column justify-content-center">
                <div class="mb-4">
                    <label class="fs-5 mb-2 fw-bold" for="username">성</label>
                    {{ form.last_name }}
                </div>
                <div class="mb-4">
                    <label class="mb-2 fs-5 fw-bold" for="username">이름</label>
                    {{ form.first_name }}
                </div>
                <div class="mb-4">
                    <label class="mb-2 fs-5 fw-bold" for="username">이메일</label>
                    {{ form.email }}
                </div>
                <input class="w-100 mt-4 btn btn-outline-secondary" type="submit" value="확인">
            </section>
        </form>
        <!-- go to password change page -->
        <div class="pe-5 w-75 d-flex justify-content-end">
            <a class="btn btn-outline-secondary me-3" href="{% url 'accounts:change_password' %}">비밀번호수정</a>
            <form action="{% url 'accounts:delete' %}" method='POST'>
                {% csrf_token %}
                <button type="button" class="btn btn-outline-secondary" role="button" data-bs-toggle="modal" data-bs-target="#confirm-modal">회원탈퇴</button>
            </form>
        </div>
    </div>
</main>
<!-- Modal -->
<div class="modal fade" id="confirm-modal" tabindex="-1" aria-labelledby="confirm-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirm-modal-label">회원탈퇴 확인</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                정말로 회원탈퇴를 하시겠습니까?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                <button type="button" class="btn btn-danger" onclick="submitForm()">회원탈퇴</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block script %}
<script src="{% static 'accounts/js/update__image.js' %}"></script>
<script src="{% static 'accounts/js/update__delete-user.js' %}"></script>
{% endblock script %}