accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/<str:username>', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    # post관련 url
    path('', views.posts, name='posts'),
    path('category/<str:subject>/', views.category, name='category'),
    path('<int:post_pk>/', views.post, name='post'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),


    # review관련 url
    path('<int:post_pk>/reviews/<int:review_pk>/', views.review_detail, name='review_detail'),
    path('<int:post_pk>/reviews/', views.review_create , name='review_create'),
    path('<int:post_pk>/reviews/<int:review_pk>/update/', views.review_update, name='review_update'),
    path('<int:post_pk>/reviews/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    path('<int:post_pk>/reviews/<int:review_pk>/likes/', views.review_likes, name='review_likes',),
    # path('<int:post_pk>/emotes/<int:emotion>/', views.emotes, name='emotes'),


    # comment관련 url
    path('<int:post_pk>/reviews/<int:review_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:post_pk>/reviews/<int:review_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),


    # 기타 url
    path('search/', views.search, name="search"),
    path('tags/<int:tag_pk>/', views.tagged, name='tagged'),
    path('<int:post_pk>/recomment/', views.recomment, name='recomment'),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
import os
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail
from django.conf import settings
from django.utils import timezone
from datetime import timedelta,datetime
from taggit.managers import TaggableManager

# Create your models here.
class Profile(models.Model):
    image = models.ImageField(blank=True, upload_to='images/profile/')
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(200, 200)],
        format='JPEG',
        options={'quality': 80}
    )


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    title = models.CharField(max_length=50)
    address = models.CharField(max_length=30)
    phone_number = models.CharField(max_length=30, blank=True)
    menu = models.CharField(max_length=200)
    hours = models.CharField(max_length=30)
    information = models.CharField(max_length=200, blank=True)
    category = models.CharField(max_length=10)
    image = models.ImageField(blank=True, null=True, upload_to='images/post/%Y/%m/%d/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager(blank=True)


    def str(self):
        return self.title
    
    def count_likes_user(self):
        return self.like_users.count()

    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, str(self.image)))
        super(Post, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_post = Post.objects.get(id=self.id)
            if self.image != old_post.image:
                if old_post.image:
                    os.remove(os.path.join(settings.MEDIA_ROOT, str(old_post.image.path)))
        super(Post, self).save(*args, **kwargs)

    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    image = models.ImageField(blank=True, null=True, upload_to='images/review/%Y/%m/%d/')
    content = models.CharField(max_length=200)
    rating = models.FloatField(verbose_name='평점')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def star_rating(self):
        rounded_rating = self.rating
        return '⭐' * int(rounded_rating) + '☆' * (rounded_rating % 1 == 0.5)
    
    def count_likes_user(self):
        return self.like_users.count()
    
    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, str(self.image)))
        super(Review, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_review = Review.objects.get(id=self.id)
            if self.image != old_review.image:
                if old_review.image:
                    os.remove(os.path.join(settings.MEDIA_ROOT, str(old_review.image.path)))
        super(Review, self).save(*args, **kwargs)

    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False


class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')
    content = models.CharField(max_length=200)
    parent_comment = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def count_likes_user(self):
        return self.like_users.count()
    
    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False
    
    
class ReviewPhoto(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='reviews/photos/')
    
    def __str__(self):
        return self.content
    
    def delete(self, *args, **kargs):
        if self.photo:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.photo))
        super(ReviewPhoto, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_reviewPhoto = ReviewPhoto.objects.get(id=self.id)
            if self.photo != old_reviewPhoto.photo:
                if old_reviewPhoto.photo:
                    os.remove(os.path.join(settings.MEDIA_ROOT, old_reviewPhoto.photo.path))
        super(ReviewPhoto, self).save(*args, **kwargs)


class Emote(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    emotion = models.CharField(max_length=10)


class ReComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    content = models.CharField('대댓글', max_length=150)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width='device-width', initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!--favicon-->
    <link rel="short icon" href="{% static 'img/favicon.ico' %}">
    {% block style %}{% endblock style %}
    <!--title-->
</head>
<body>
    <header class="navbar bg-body-tertiary sticky-top">
        <div class="container">

            {% comment %}
            
            <!-- header__logo -->
            <div class='col-4 d-flex justify-content-center'>
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img src="{% static 'img/today-cafe_Logo.svg' %} " alt="logo" width="70px">
                </a>
            </div>
            
            <!-- header__account-link -->
            <div class="col-4 d-flex justify-content-end">
                {% if request.user.is_authenticated %}
                    <div class="d-flex align-items-center gap-3">
                        <a  href="{% url 'accounts:profile' user.username %}" class="d-flex align-items-center gap-3">
                            <div class='base--profile--img_form d-flex justify-content-center'>
                            {% if request.user.profile_image %}
                                <img src="{{ request.user.profile_image.url }}" alt="profile_image" class='profile-image'>
                            {% else %}
                                <img src="{% static 'accounts/img/no_profile.jpeg' %}" alt="profile_image" class='profile-image'>
                            {% endif %}
                            </div>
                            <div class="base--log_user"><b>{{ request.user }}</b> 님</div>
                        </a>
                        <form action="{% url 'accounts:logout' %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" value="로그아웃" class="btn btn-secondary base--log_btn">
                        </form>
                    </div>
                {% else %}
                    <div class="d-flex align-items-center gap-3">
                        <a class="btn btn-secondary base--log_btn d-flex align-items-center" href="{% url 'accounts:login' %}"><span>로그인</span></a>
                        <a class="btn btn-secondary base--log_btn d-flex align-items-center" href="{% url 'accounts:signup' %}"><span>회원가입</span></a>
                    </div>
                {% endif %}
            </div>

            <!-- 검색 창 -->
            <div class="container d-flex justify-content-center align-items-center my-3">
                <form class="d-flex justify-content-center align-items-center search_bar" method="GET" action="{% url 'posts:search' %}">
                <span class="material-symbols-outlined text-danger ms-2">
                    search
                </span>
                <input class="search_bar__input" type="text" placeholder="검색어를 입력해주세요" name="q" aria-label="Search">
                <button class="btn btn-danger search_btn d-flex justify-content-center align-items-center me-0" type="submit">검색</button>
                </form>
            </div> {% endcomment %}



            <!-- header__location-btn -->
            <div class="col-4">
                <button class="navbar-toggler d-flex align-items-center border-0 p-0 base--side_btn" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>

            <div class="col-4 d-flex justify-content-center align-items-center">
                <!-- header__logo -->
                <div>
                    <a class="navbar-brand" href="{% url 'index' %}">
                        <img src="{% static 'img/today-cafe_Logo.svg' %} " alt="logo" width="70px">
                    </a>
                </div>
                
                <!-- 검색 창 -->
                <div>
                    <form class="d-flex justify-content-center align-items-center search_bar ps-2" method="GET" action="{% url 'posts:search' %}">
                        <span class="material-symbols-outlined text-danger">
                            search
                        </span>
                        <input class="search_bar__input" type="text" placeholder="검색어를 입력해주세요" name="q" aria-label="Search">
                        <button class="btn btn-danger search_btn d-flex justify-content-center align-items-center me-0" type="submit">검색</button>
                    </form>
                </div>
            </div>
            
            <!-- header__account-link -->
            <div class="col-4 d-flex justify-content-end">
                {% if request.user.is_authenticated %}
                    <div class="d-flex align-items-center gap-3">
                        <a  href="{% url 'accounts:profile' user.username %}" class="d-flex align-items-center gap-3">
                            <div class='base--profile--img_form d-flex justify-content-center'>
                            {% if request.user.profile_image %}
                                <img src="{{ request.user.profile_image.url }}" alt="profile_image" class='profile-image'>
                            {% else %}
                                <img src="{% static 'accounts/img/no_profile.jpeg' %}" alt="profile_image" class='profile-image'>
                            {% endif %}
                            </div>
                            <div class="base--log_user"><b>{{ request.user }}</b> 님</div>
                        </a>
                        <form action="{% url 'accounts:logout' %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" value="로그아웃" class="btn btn-secondary base--log_btn">
                        </form>
                    </div>
                {% else %}
                    <div class="d-flex align-items-center gap-3">
                        <a class="btn btn-secondary base--log_btn d-flex align-items-center" href="{% url 'accounts:login' %}"><span>로그인</span></a>
                        <a class="btn btn-secondary base--log_btn d-flex align-items-center" href="{% url 'accounts:signup' %}"><span>회원가입</span></a>
                    </div>
                {% endif %}
            </div>

            <!-- menu 클릭 시 오른쪽에서 pop-up되는 카테고리-->
            <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <!-- pop-up title-->
                <div class="offcanvas-header mt-3">
                    <h5 class="offcanvas-title ms-3" id="offcanvasNavbarLabel">MENU</h5>
                    <button type="button" class="btn-close me-3" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <!-- 카테고리 detail -->
                <div class="offcanvas-body">
                    <ul class="navbar-nav ms-3 gap-4">
                        <li class="nav-item">
                            <a class="d-flex align-items-center gap-2 base--cate_btn" href="{% url 'index' %}">
                                <span class="material-symbols-outlined">home</span>
                                <span>홈</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="{% if subject == 'all' %}text-danger{% endif %} d-flex align-items-center gap-2 base--cate_btn" href="{% url 'posts:posts' %}">
                                <span class="material-symbols-outlined">menu</span>
                                <span>모든 카페</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="{% if subject == '카공 모각코' %}text-danger{% endif %} d-flex align-items-center gap-2 base--cate_btn" href="{% url 'posts:category' subject='카공 모각코' %}">
                                <span class="material-symbols-outlined">stylus</span>
                                <span>카공 / 모각코</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="{% if subject == '펫 카페' %}text-danger{% endif %} d-flex align-items-center gap-2 base--cate_btn" href="{% url 'posts:category' subject='펫 카페' %}">
                                <span class="material-symbols-outlined">pets</span>
                                <span>펫 동반카페</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="{% if subject == '북 카페' %}text-danger{% endif %} d-flex align-items-center gap-2 base--cate_btn" href="{% url 'posts:category' subject='북 카페' %}">
                                <span class="material-symbols-outlined">import_contacts</span>
                                <span>북 카페</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </header>
    {% block content %}{% endblock content %}
    <footer class="navbar bg-body-tertiary d-flex align-items-center">
        <div class="container my-3">

            <!-- footer__logo-copyright -->
            <section>
                <div>
                    <img src="{% static 'img/today-cafe_Logo.svg' %} " alt="logo" width="50px">
                    <span>Today Cafe</span>
                </div>
                <div>Copyright &copy; 2023 team 5. 이리5쇼</div>
                <div>multi-campus KDT 2th semi-project</div>
            </section>
            
            <!-- footer__creater-github -->
            <section class="d-flex gap-3">
                <div class="me-4"><b>Members</b></div>
                <div class="d-flex flex-column gap-3">
                    <a class="text-decoration-none text-secondary" href="https://github.com/zzgh06">최충현</a>
                    <a class="text-decoration-none text-secondary" href="https://github.com/JeonggonCho">조정곤</a>
                </div>
                <div class="d-flex flex-column gap-3">
                    <a class="text-decoration-none text-secondary" href="https://github.com/nninzy">김민지</a>
                    <a class="text-decoration-none text-secondary" href="https://github.com/jeonseongjae98">전성재</a>
                </div>
            </section>
        </div>
    </footer>

    <!-- top 버튼 -->
    <div id="scroll-to-top-button" class="btn btn-danger d-flex align-items-center justify-content-center">
        <span class="material-symbols-outlined fs-1">expand_less</span>
    </div>

    <script src="{% static 'js/baseTop.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    {% block script %}{% endblock script %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
<title>투데이 카페</title>
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock style %}


{% block content %}
<div class="loading-splash">
    <div class="loading-splash__container">
        <img src={% static 'img/today-cafe_Logo.svg' %} alt="">
        <span>Loading</span>
    </div>
</div>
<main class="container my-3">
    <!-- carousel 화면 -->
    <section class="index__clock-section d-flex justify-content-between">
        <h4 class="index__clock fw-bold">00:00:00</h4>
        <h5 class="index__menu fw-bold">오늘의 메뉴 추천 : <span class="random-menu">없음</span></h5>
    </section>
    <section class="index__carousel d-flex justify-content-center mt-3 mb-5">
        <div id="carouselExampleIndicators" class="carousel slide w-100">
            <div class="carousel-indicators mb-1">
                <button type="button" class="active mx-2 rounded-circle" style="width: 0.8rem; height: 0.8rem;"data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" class="mx-2 rounded-circle" style="width: 0.8rem; height: 0.8rem;"data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" class="mx-2 rounded-circle" style="width: 0.8rem; height: 0.8rem;"data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="https://cdn.psnews.co.kr/news/photo/202206/2009891_52943_2236.jpg" alt="...">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="https://www.shinsegaegroupnewsroom.com/wp-content/uploads/2022/02/%EC%8A%A4%ED%83%80%EB%B2%85%EC%8A%A4_%EB%B3%B8%EB%AC%B8_2.png" alt="...">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="https://www.shinsegaegroupnewsroom.com/wp-content/uploads/2021/02/%EC%8A%A4%ED%83%80%EB%B2%85%EC%8A%A4_%EB%B3%B8%EB%AC%B83.png" alt="...">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </section>
    <!-- articles-recent-->
    <section class="articles-recent--sm-card mb-5">
        <h3 class="fw-bold mb-4">신규 등록된 카페</h3>
        <div class="row row-cols-4 g-4">
            {% for post in recent_posts %}
            <article class="col">
                <div class="card">
                    <div class="article-thumbnail__img position-relative d-flex align-items-center justify-content-center" style="height: 200px; overflow: hidden;">
                        <img class="card-img-top w-100" src="{{ post.image.url }}" alt="...">
                        <div class="article-thumbnail__img__like position-absolute top-0 end-0 m-3 d-flex justify-content-center align-items-center">
                            <span class="material-symbols-outlined">favorite</span>
                        </div>
                    </div>
                    <a href="" class="card-body bg-light">
                        <span class="card-title fw-bold mb-3">{{ post.title }}</span>
                        <div class="card-content card-text col-12 text-truncate mb-2"><span class="me-3 fw-bold">주소</span>{{ post.address }}</div>
                        <div class="d-flex align-items-center justify-content-end">
                            <span class="material-symbols-outlined me-2">favorite</span>
                            <span class="me-3">{{ post.count_likes_user }}</span>
                            <span class="material-symbols-outlined me-2">mode_comment</span>
                            <span>{{ post.review_set.all|length }}</span>
                        </div>
                    </a>
                </div>
            </article>
            {% endfor %}
        </div>
    </section>
</main>
{% endblock content %}
{% block script %}
<script src="{% static 'js/index__clock.js' %}"></script>
{% endblock script %}