accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/<str:username>', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    # post관련 url
    path('', views.posts, name='posts'),
    path('category/<str:subject>/', views.category, name='category'),
    path('<int:post_pk>/', views.post, name='post'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),


    # review관련 url
    path('<int:post_pk>/reviews/<int:review_pk>/', views.review_detail, name='review_detail'),
    path('<int:post_pk>/reviews/', views.review_create , name='review_create'),
    path('<int:post_pk>/reviews/<int:review_pk>/update/', views.review_update, name='review_update'),
    path('<int:post_pk>/reviews/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    path('<int:post_pk>/reviews/<int:review_pk>/likes/', views.review_likes, name='review_likes',),
    # path('<int:post_pk>/emotes/<int:emotion>/', views.emotes, name='emotes'),


    # comment관련 url
    path('<int:post_pk>/reviews/<int:review_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:post_pk>/reviews/<int:review_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),


    # 기타 url
    path('search/', views.search, name="search"),
    path('tags/<int:tag_pk>/', views.tagged, name='tagged'),
    path('<int:post_pk>/recomment/', views.recomment, name='recomment'),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
import os
from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail
from django.conf import settings
from django.utils import timezone
from datetime import timedelta,datetime
from taggit.managers import TaggableManager

# Create your models here.
class Profile(models.Model):
    image = models.ImageField(blank=True, upload_to='images/profile/')
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(200, 200)],
        format='JPEG',
        options={'quality': 80}
    )


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    title = models.CharField(max_length=50)
    address = models.CharField(max_length=30)
    phone_number = models.CharField(max_length=30, blank=True)
    menu = models.CharField(max_length=200)
    hours = models.CharField(max_length=30)
    information = models.CharField(max_length=200, blank=True)
    category = models.CharField(max_length=10)
    image = models.ImageField(blank=True, null=True, upload_to='images/post/%Y/%m/%d/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager(blank=True)


    def str(self):
        return self.title
    
    def count_likes_user(self):
        return self.like_users.count()

    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, str(self.image)))
        super(Post, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_post = Post.objects.get(id=self.id)
            if self.image != old_post.image:
                if old_post.image:
                    os.remove(os.path.join(settings.MEDIA_ROOT, str(old_post.image.path)))
        super(Post, self).save(*args, **kwargs)

    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    image = models.ImageField(blank=True, null=True, upload_to='images/review/%Y/%m/%d/')
    content = models.CharField(max_length=200)
    rating = models.FloatField(verbose_name='평점')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def star_rating(self):
        rounded_rating = self.rating
        return '⭐' * int(rounded_rating) + '☆' * (rounded_rating % 1 == 0.5)
    
    def count_likes_user(self):
        return self.like_users.count()
    
    def delete(self, *args, **kargs):
        if self.image:
            os.remove(os.path.join(settings.MEDIA_ROOT, str(self.image)))
        super(Review, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_review = Review.objects.get(id=self.id)
            if self.image != old_review.image:
                if old_review.image:
                    os.remove(os.path.join(settings.MEDIA_ROOT, str(old_review.image.path)))
        super(Review, self).save(*args, **kwargs)

    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False


class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')
    content = models.CharField(max_length=200)
    parent_comment = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def count_likes_user(self):
        return self.like_users.count()
    
    @property
    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False
    
    
class ReviewPhoto(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='reviews/photos/')
    
    def __str__(self):
        return self.content
    
    def delete(self, *args, **kargs):
        if self.photo:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.photo))
        super(ReviewPhoto, self).delete(*args, **kargs)

    def save(self, *args, **kwargs):
        if self.id:
            old_reviewPhoto = ReviewPhoto.objects.get(id=self.id)
            if self.photo != old_reviewPhoto.photo:
                if old_reviewPhoto.photo:
                    os.remove(os.path.join(settings.MEDIA_ROOT, old_reviewPhoto.photo.path))
        super(ReviewPhoto, self).save(*args, **kwargs)


class Emote(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    emotion = models.CharField(max_length=10)


class ReComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    content = models.CharField('대댓글', max_length=150)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

posts/forms.py
from django import forms
from .models import Post, Comment, Review, ReComment
from taggit.forms import TagField, TagWidget


class PostForm(forms.ModelForm):
    title = forms.CharField(
        label='카페명',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '카페이름을 입력해주세요',
            },
        ),
    )


    address = forms.CharField(
        label='주소',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '주소를 입력해주세요',
            },
        ),
    )


    phone_number = forms.CharField(
        label='전화번호',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '전화번호를 입력해주세요',
            },
        ),
    )


    menu = forms.CharField(
        label='메뉴',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '카페의 대표메뉴를 입력해주세요',
            },
        ),
    )


    hours = forms.CharField(
        label='영업시간',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '영업시간 및 휴무일을 입력해주세요',
            },
        ),
    )

    
    information = forms.CharField(
        label='편의시설 정보',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '방문객을 위한 편의시설 정보를 입력해주세요',
            },
        ),
    )

    CHOICES=[('카공 모각코', '카공/모각코'), ('펫 카페', '펫 카페'), ('북 카페', '북 카페')]
    category = forms.ChoiceField(
        label='카테고리',
        widget=forms.Select(
            attrs={
                'class': 'form-select',
            }
        ),
        choices=CHOICES,
    )

    image = forms.ImageField(
        label='이미지',
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control',
            },
        )
    )

    tags = forms.CharField(
        label='태그',
        widget=TagWidget(
            attrs={
                'class': 'form-control',
                'placeholder': '태그는 콤마(,)로 구분하여 작성해주세요' 
            }
        )
    )


    class Meta:
        model = Post
        fields = ('title', 'address', 'phone_number', 'menu', 'hours', 'information', 'category', 'image', 'tags',)


class ReviewForm(forms.ModelForm):
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': 4,
            },
        ),
    )


    rating = forms.FloatField(
        label='평점',
        widget=forms.Select(
            choices=[
                (1, '⭐' * 1 + '☆' * 4),
                (2, '⭐' * 2 + '☆' * 3),
                (3, '⭐' * 3 + '☆' * 2),
                (4, '⭐' * 4 + '☆' * 1),
                (5, '⭐' * 5),
            ],
            attrs={
                'class': 'form-select',
            },
        ),
    )

    
    image = forms.ImageField(
        label='이미지',
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control form-control-sm',
                'multiple': 'True',
            },
        ),
        required=False,
    )
    class Meta:
        model = Review
        fields = ('content', 'rating','image',)


class ReCommentForm(forms.ModelForm):
    class Meta:
        model = ReComment
        fields = ('content', 'comment')
    


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label='Comment',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control focus-ring focus-ring-danger',
            },
        ),
    )
    class Meta:
        model = Comment
        fields = ('content',)

posts/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
<link rel="stylesheet" href="{% static 'posts/css/posts.css' %}">
{% endblock style %}


{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"> Navbar </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="#"> Home </a></li>
                <li class="nav-item"><a class="nav-link" href="#"> Link </a></li>
            </ul>
            <form class="d-flex" method="GET" action="{% url 'posts:search' %}">       
              <input class="form-control me-2" type="text" placeholder="Search" name="q" aria-label="Search">
              <button class="btn btn-outline-success" type="submit"> Search </button>
            </form>
        </div>
    </div>
</nav>


  <h1>Index</h1>
  {% if request.user.is_authenticated %}
    <h3>{{ user }}님</h3>
    <a href="{% url 'accounts:profile' user.username %}">프로필</a>
    <form action="{% url 'accounts:logout' %}" method='POST'>
      {% csrf_token %}
      <input class="btn btn-outline-secondary text-center" type='submit' value='Logout'>
    </form>
    <form action="{% url 'accounts:delete' %}" method='POST'>
      {% csrf_token %}
      <button type="submit" class="btn btn-outline-secondary" role="button">회원탈퇴</button>
    </form>
    <a href="{% url 'accounts:update' %}">회원정보수정</a>
  {% else %}
    <a href="{% url 'accounts:login' %}">Login</a>
    <a href="{% url 'accounts:signup' %}">Signup</a>
  {% endif %}

  <h1>POST</h1>
  <a href="{% url 'posts:create' %}">[CREATE]</a>

  {% for post in posts %}
    <p>작성자: 
      <a href="{% url 'accounts:profile' post.user.username %}">{{ post.user }}</a>
    </p>
    <p>제목: 
      <a href="{% url 'posts:detail' post.pk %}">{{ post.title }}</a>
    </p>
    <p>내용: {{ post.content }}</p>
    <form action="{% url 'posts:likes' post.pk %}" method="POST">
      {% csrf_token %}
      {% if request.user in post.like_users.all %}
        <input type="submit" value="좋아요 취소">
      {% else %}
        <input type="submit" value="좋아요">
      {% endif %}
    </form>
    <hr>
    {% endfor %}

    <main>
      <div class="container my-5">
        <!-- 카테고리 -->
        <div class="mb-5">
          <h2 class="mb-4"><strong>카테고리</strong></h2>
          <div class="d-flex gap-3">
            <a href="{% url 'posts:index' %}" class="posts--cate_btn d-flex gap-3 align-items-center justify-content-center">
              <span class="material-symbols-outlined">
                menu
              </span>
              <h5 class="m-0">모든 카페</h5>
            </a>
            <a href="{% url 'posts:index' %}" class="posts--cate_btn d-flex gap-3 align-items-center justify-content-center">
              <span class="material-symbols-outlined">
                stylus
              </span>
              <h5 class="m-0">카공/모각코</h5>
            </a>
            <a href="{% url 'posts:index' %}" class="posts--cate_btn d-flex gap-3 align-items-center justify-content-center">
              <span class="material-symbols-outlined">
                pets
              </span>
              <h5 class="m-0">펫 카페</h5>
            </a>
            <a href="{% url 'posts:index' %}" class="posts--cate_btn d-flex gap-3 align-items-center justify-content-center">
              <span class="material-symbols-outlined">
                import_contacts
              </span>
              <h5 class="m-0">북 카페</h5>
            </a>
          </div>
        </div>

        <!-- 각각의 카테고리 목록 -->
          <div>
            <div class="d-flex">
              <h2 class="mb-4"><strong>모든 카페</strong></h2>
            </div>

            {% for post in posts %}
            <div class="posts--cate_form d-flex gap-5 mb-5">
              <!-- 카테고리 카페 이미지 -->
              <div class="posts--cate_img_form">
                <img src="https://odden1.speedgabia.com/static/bb/lists/spot-n03-s02/spot_f_n03-s02-01.jpg" alt="">
              </div>
              <!-- 카테고리 카페 이름 -->
              <div class="my-5">
                <div class="d-flex flex-grow-1 align-items-center gap-3">
                  <div class="posts--cate_form_icon d-flex justify-content-center align-items-center"><span class="material-symbols-outlined">stylus</span></div>
                  <h2><strong>스터디 카페</strong></h2>

                  <!-- 좋아요 버튼 -->
                  <div>
                    <form action="{% url 'posts:likes' post.pk %}" method="POST">
                      {% csrf_token %}
                      {% if request.user in post.like_users.all %}
                        <button type="submit" class="border-0">
                          <span class="material-symbols-outlined">
                            favorite
                          </span>
                        </button>
                      {% else %}
                        <button type="submit" class="border-0">
                          <span class="material-symbols-outlined">
                            favorite
                          </span>
                        </button>
                      {% endif %}
                    </form>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
      </div>
    </main>
{% endblock content %}

posts/templates/posts/post.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
<link rel="stylesheet" href="{% static 'posts/css/post.css' %}">
{% endblock style %}


{% block content %}
<main>
    <div class='container my-5'>
        <div class="d-flex mb-3">
            <div class="d-flex flex-grow-1 align-items-center gap-3">
                <div class="post--cate_form_icon d-flex justify-content-center align-items-center"><span class="material-symbols-outlined">stylus</span></div>
                <h2 id="post-title"><strong>{{ post.title }}</strong></h2>
                <div>
                    <form class="like-forms" data-post-id="{{ post.pk }}">
                    {% csrf_token %}
                    {% if request.user in post.like_users.all %}
                        <button type="submit" class="border-0 p-0 post--like_btn" id="like-{{ post.pk }}">
                        <span class="material-symbols-outlined">
                            favorite
                        </span>
                        </button>
                    {% else %}
                        <button type="submit" class="border-0 p-0 post--unlike_btn" id="like-{{ post.pk }}">
                        <span class="material-symbols-outlined">
                            favorite
                        </span>
                        </button>
                    {% endif %}
                    </form>
                </div>
            </div>
            <a href="{% url 'posts:review_create' post.pk %}" class="btn btn-danger post--create_btn d-flex align-items-center justify-content-center gap-3"><span class="material-symbols-outlined">edit_square</span><div>리뷰작성</div></a>
        </div>

        <!-- 지도 -->
        <div id="map" class="post--map_form w-100 my-3"></div>

        <div class="d-flex mb-3">
            <div class="w-100">
                <!-- 카페 기본정보 -->
                <div class="post--info_form d-flex gap-3">
                    <div class="d-flex flex-column justify-content-center w-100">
                        <!-- 주소 정보 -->
                        <div class="d-flex align-items-center mb-3">
                            <div class="col-3 d-flex align-items-center gap-2">
                                <span class="material-symbols-outlined">location_on</span>
                                <h6 class="m-0"><strong>주소</strong></h6>
                            </div>
                            <div class=" flex-grow-1" id="post-address">{{ post.address }}</div>
                        </div>
    
                        <!-- 전화번호 -->
                        <div class="d-flex align-items-center mb-3">
                            <div class="col-3 d-flex align-items-center gap-2">
                                <span class="material-symbols-outlined">call</span>
                                <h6 class="m-0"><strong>전화번호</strong></h6>
                            </div>
                            <div>{{ post.phone_number }}</div>
                        </div>
    
                        <!-- 영업시간 -->
                        <div class="d-flex align-items-center mb-3">
                            <div class="col-3 d-flex align-items-center gap-2">
                                <span class="material-symbols-outlined">schedule</span>
                                <h6 class="m-0"><strong>영업시간</strong></h6>
                            </div>
                            <div>{{ post.hours }}</div>
                        </div>
    
                        <!-- 메뉴 -->
                        <div class="d-flex align-items-center mb-3">
                            <div class="col-3 d-flex align-items-center gap-2">
                                <span class="material-symbols-outlined">summarize</span>
                                <h6 class="m-0"><strong>메뉴</strong></h6>
                            </div>
                            <div>{{ post.menu }}</div>
                        </div>
    
                        <!-- 편의시설/정보 -->
                        <div class="d-flex align-items-center mb-4">
                            <div class="col-3 d-flex align-items-center gap-2">
                                <span class="material-symbols-outlined">info</span>
                                <h6 class="m-0"><strong>편의시설 정보</strong></h6>
                            </div>
                            <div>{{ post.information }}</div>
                        </div>
    
                        <!-- 태그 -->
                        <div class="d-flex align-items-center gap-3 mb-3">
                            {% for tag in tags %}
                                <a href="{% url 'posts:tagged' tag.pk %}">
                                    <div class="post--tag">#{{ tag.name }}</div>
                                </a>
                            {% endfor %}
                        </div>
    
                        <!-- 카페정보 수정 --> 
                        <div class="d-flex align-items-center">
                            <span class="me-3 text-secondary update_font">최근 업데이트 : {{ post.updated_at|date:'Y-m-d' }}</span>
                            <div class="d-flex align-items-center gap-3">
                                {% if request.user == post.user %}
                                    <a class="post--update_btn" href="{% url 'posts:update' post.pk %}"><span>수정</span></a>
                                    <form action="{% url 'posts:delete' post.pk %}" method='POST' class="p-0 m-0">
                                        {% csrf_token %}
                                        <input type='submit' class="p-0 border-0 post--delete_btn" value='삭제' onclick="return confirm('삭제 하시겠습니까?')">
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <!-- 카페사진 -->
                    <div class="post--img_form w-75">
                        <img src="{{ post.image.url }}" alt="">
                    </div>
                </div>
            </div>
        </div>

        <hr>

        <!-- 리뷰 -->
        <h4 class="my-4"><strong>리뷰 ({{ reviews|length }})</strong></h4>

        {% if reviews %}
            {% for review in reviews %}
            <div class="post--detail_form mb-3">
                <div class="d-flex gap-4">
                    <!-- 리뷰 프로필 이미지 -->
                    <div class="col-1 d-flex flex-column align-items-center gap-3">
                        {% if review.user.profile_image %}
                            <div class='profile--img_medium_form'>
                                <img src="{{ review.user.profile_image.url }}" alt="">
                            </div>
                        {% else %}
                            <div class='profile--img_medium_form'>
                                <img src="{% static 'accounts/img/no_profile.jpeg' %}" alt="profile_image">
                            </div>
                        {% endif %}
                        <a href='{% url 'accounts:profile' review.user.username %}'><strong>{{ review.user.username }}</strong></a>

                        <!-- 타인이면 팔로우 버튼 -->
                        {% if request.user != review.user %}
                            <form id="follow-form" data-user-id="{{ review.user.pk }}" class="w-100">
                                {% csrf_token %}
                                {% if request.user in review.user.followers.all %}
                                    <input class="btn btn-secondary w-100" type="submit" value="언팔로우">
                                {% else %}
                                    <input class="btn btn-secondary w-100" type="submit" value="팔로우">
                                {% endif %}
                            </form>
                        {% endif %}
                    </div>

                    <div class="col-10 d-flex flex-grow-1 flex-column w-75">
                        <div class="mb-3">
                            {% if review.created_string == False %}
                                {{ review.created_at|date:'Y-m-d' }}
                            {% else %}
                                {{ review.created_string }}
                            {% endif %}
                        </div>
                        <a href="{% url 'posts:review_detail' post.pk review.pk %}" class="d-flex gap-4">
                            <div class="post--review_photo_form">
                                {% if review.reviewphoto_set.exists %}
                                    <img src="{{ review.reviewphoto_set.first.photo.url }}" alt="">
                                {% else %}
                                    <img src="{% static 'posts/img/no_img.jpg' %}" alt="">
                                {% endif %}
                            </div>
                            <div class="d-flex flex-column gap-3">
                                <div class="fs-5">{{ review.star_rating }}</div>
                                <div class="mb-4">{{ review.content }}</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-1 d-flex flex-column align-items-end">
                        <form class="review-like-forms" data-post-id="{{ post.pk }}" data-review-id="{{ review.pk }}">
                        {% csrf_token %}
                        {% if request.user in review.like_users.all %}
                            <button type="submit" class="border-0 post--like_btn" id="like-{{ post.pk }}-{{ review.pk }}">
                            <span class="material-symbols-outlined">
                                favorite
                            </span>
                            </button>
                        {% else %}
                            <button type="submit" class="border-0 post--unlike_btn" id="like-{{ post.pk }}-{{ review.pk }}">
                            <span class="material-symbols-outlined">
                                favorite
                            </span>
                            </button>
                        {% endif %}
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
        <div class="d-flex flex-column align-items-center text-secondary">
            <h5>생성된 리뷰가 없습니다</h5>
        </div>
        {% endif %}
    </div>
</main>
{% endblock content %}

{% block script %}
    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=3b8f429608439fe66cf463070bdbdb14&libraries=services"></script>
    <script src="{% static 'posts/js/postMap.js' %}"></script>
    <script src="{% static 'posts/js/postLike.js' %}"></script>
    <script src="{% static 'posts/js/postFollow.js' %}"></script>
    <script src="{% static 'posts/js/postReviewLike.js' %}"></script>
{% endblock script %}

posts/templates/posts/post_create.html
{% extends 'base.html' %}
{% load static %}


{% block style %}

{% endblock style %}


{% block content %}
  <h3>CREATE</h3>
  <form action="{% url 'posts:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="글 작성"></input>
  </form>
{% endblock content %}

posts/templates/posts/review_create.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'posts/css/create.css' %}">
{% endblock style %}

{% block content %}
<main>
    <div class="container my-5 create_form">
        <div class="d-flex align-itmes-center justify-content-center mb-3 position-relative">
            <a href="{% url 'posts:post' post.pk %}" class="position-absolute start-0 create--back_btn">
                <span class="material-symbols-outlined mt-2">
                    arrow_back_ios
                </span>
            </a>
            <h2><strong>리뷰 작성</strong></h2>
        </div>
        <hr>
        <form action="{% url 'posts:review_create' post.pk %}" method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            {% for field in review_form %}
            <div>
                <p>{{ field.label }}</p>
                <p>{{ field }}</p>
            </div>
            {% endfor %}
            <input type="submit" class="btn btn-secondary create--submit_btn" value="리뷰 작성"></input>
        </form>
    </div>
</main>
{% endblock content %}